### ISSUE TITLE
Message receiving stops if done() is not invoked

### ISSUE THREAD

**Issue by kavuri** [bbc/sqs-consumer#22] opened 2016-01-01 10:16 UTC
From the documentation of sqs-consumer, I understood that a message from the queue would be deleted only if "done()" is called in handleMessage. I have a usecase that I want the message to be left in the queue after being processed. But when the run the following code, node exits after processing a single message and only starts polling only if I call done()

Is this expected?
```
var Consumer = require('sqs-consumer');
var AWS = require('aws-sdk');
AWS.config.loadFromPath('../config/aws-config.json');
var app = Consumer.create({
  queueUrl: 'https://sqs.us-east-1.amazonaws.com/123/myQ',
  waitTimeSeconds: 5,
  handleMessage: function (message, done) {
    console.log(message);
    //done();
  },
});
app.on('error', function(err) {
    console.log(err.message);
});
app.start();
```

**Comment by robinjmurphy** [comment] 2016-01-01 11:01
I think this is the behaviour I'd expect. When you don't call `done` in your `handleMessage` function, there are no more callbacks left to be called and the Node process will exit.

This library is designed specifically for task queues, where messages are processed and then deleted. If you need to inspect a queue or interact with it in another way, you might want to use the AWS library directly.

**Comment by kavuri** [comment] 2016-01-01 16:04
done() is overloaded with two pieces of functionality:
1. It deletes the currently processed message
2. It re-polls the queue with long poll

Is there a way to dis-associate this? The reason being that during the processing of a message (which happens in an async loop), I would like to leave the message in queue, but meanwhile, if there are new messages in queue, I would like to process them. This does not seem to be possible. Is there a way to not overload this functionality?

**Comment by robinjmurphy** [comment] 2016-01-01 16:17
That's the intended behaviour. We _want_ to couple those two actions together so that polling doesn't restart until the current message/batch of messages has been processed.

You can ask for more than one message at once using the `batchSize` option but polling won't restart until you've finished processing all of the messages in the current batch.

This is to stop each Node process from taking on too many messages at once. It also provides a predictable workload for each consumer. We fix the batch size and scale horizontally to cope with the number of messages on a queue.

**Comment by kavuri** [comment] 2016-01-01 16:29
The processing of a message in my usecase can go anywhere between few secs to minutes. I have modified the code to invoke `consumer._poll() in the handleMessage() and deleteMessage(), like

```
  async.series([
    function handleMessage(done) {
      consumer.handleMessage(message, done);
      consumer._poll(); //SK
    },
    function deleteMessage(done) {
      consumer._deleteMessage(message, done);
      consumer._poll(); //SK
    }
  ], function (err) {
```
Can you suggest if this is an okay change to make?

**Comment by robinjmurphy** [comment] 2016-01-01 17:39
It's not a change I'd like to introduce. We actually used to do this (re-polling immediately regardless of whether a message has been processed) but we changed it in favour of the current behaviour to make the message handling more controlled.

In particular, if the service is struggling to process messages, it shouldn't continue to consume them from the queue at the same rate. The current implementation provides some _back pressure_ on the queue when processing slows down for some reason.

If you want a different polling behaviour, I'd suggest using the AWS client directly.

I'm going to close this issue off as the current re-polling behaviour is a feature of our library.

**Closed by robinjmurphy** 2016-01-01 17:39 UTC

**Comment by cabrinoob** [comment] 2016-09-22 09:21
I have the following use case : 
A producer push tasks in SQS. Those tasks are addressed to specific consumers (A and B).

Suppose now that in the queue there is only "C" messages, A and B consumers read these tasks but leave them in queue. In that case A and B did not call done() and the polling stops. 

So my node process exits and if an A or B message is pushed it will not be consumed.

**Comment by truedat101** [comment] 2017-03-01 11:36
I'm at least on the side of the inquiry here that says the "desired behavior" should be documented clearly.  It felt like a bug when I didn't understand why it would stop suddenly.  @robinjmurphy the explanation makes sense, as you have described.  I tried out the clever patch by @kavuri and it brings up a host of other questions and potential issues which you probably don't want to support.  That said, it doesn't seem unreasonable to disable this behavior, perhaps as an unsupported mode.  But it would be great to add your explanation to the README.  Thank you.

**Comment by truedat101** [comment] 2017-03-01 18:53
And a follow on to my comment, I was puzzled that the code would exit in this condition without firing an event.  Unless  I missed the event, it appeared to just exit.

**Comment by truedat101** [comment] 2017-03-09 05:49
@kavuri maybe let's fork the changes and some configuration to try out how this might look with an option to not have this as the default behavior?

**Comment by kavuri** [comment] 2017-03-09 08:40
@truedat101 I have moved on from this and am not pursuing this anymore. Having a configuration to take this patch might be involved but adding this patch to try if it works or not should not be difficult for you

**Comment by tamal-appsbee** [comment] 2017-08-24 11:54
@robinjmurphy is there any way to skip() like done() if wnat to skip for now to process it later ?
