### ISSUE TITLE
Delete only certain message received via handleMessageBatch

### ISSUE THREAD

**Issue by TylerMatteo** [bbc/sqs-consumer#189] opened 2019-10-23 18:52 UTC
Is it possible to only delete some of the messages received in a batch? I understand that using `handleMessage` in combination with a `batchSize` greater than 1 results in them being processed one at a time but `handleMessageBatch` seems to be all or nothing. For example, if I had an API that could save multiple messages at a time and return a list of those that were successfully saved, could I use that to delete only the successfully saved messages from the queue?

**Comment by ionutale** [comment] 2019-11-12 10:11
i have the same request

**Comment by johncmunson** [comment] 2019-12-20 18:27
I also am wondering if this is possible

**Comment by ionutale** [comment] 2020-01-17 06:53
i like it

**Comment by fullc0de** [comment] 2020-03-31 03:24
Is it still ongoing?

**Comment by crh3675** [comment] 2020-05-22 21:34
Just delete your own messages then within your batch handler:

    handleMessageBatch: async (messages) => {
      messages.forEach(message => {
        // check success of message
       const success = await processMessage(message);
        if (success) {
          instance.deleteMessage(message);
        }
      });
      return Promise.resolve();
    });

**Comment by jackbraj** [comment] 2020-06-04 07:50
@crh3675 where does this instance comes from?

**Comment by crh3675** [comment] 2020-06-04 08:57
`instance` is the main variable you assign from `const app = Consumer.create({`

**Comment by jackbraj** [comment] 2020-06-04 10:18
Ok so I can manually delete a job but the problem is the library doesn't care anything and deletes all messages. Look at this in consumer.ts

```typescript
try {
      await this.executeBatchHandler(messages);
      await this.deleteMessageBatch(messages);
      messages.forEach((message) => {
        this.emit('message_processed', message);
      });
    }
```

So what's the use of deleting manually when the library wipes the whole batch

**Comment by trubi** [comment] 2021-02-11 11:42
Unfortunately, this library is useless with combination of this bug and another bug where message handlers are run in paralel even for fifo queue.

**Comment by recoiladam** [comment] 2021-04-10 08:37
> Unfortunately, this library is useless with combination of this bug and another bug where message handlers are run in paralel even for fifo queue.

Oh good, I am not the only one seeing this problem. I am using the standard `handleMessage` and every time my consumer polls, it grabs a new message even if the previous one has not finished processing. Seems like the contributors of this project are not very active in it anymore though.

**Comment by nicholasgriffintn** [comment] 2022-12-09 12:04
Whoops! Wrong one sorry 😂

**Comment by nicholasgriffintn** [comment] 2022-12-16 17:00
The resolution to https://github.com/bbc/sqs-consumer/issues/245 will provide a list of successful messages, once that's available, we can probably look at how messages are deleted.

**Comment by nicholasgriffintn** [comment] 2022-12-16 22:06
Now that 245 has been merged, I think this is now possible, once that change has been released to NPM (probably after Christmas now).

The change will mean that you can return an array of messages that you want to acknowledge, only the messages in this array will be deleted.

If that does not resolve your issue then please feel free to open a new one :).

**Closed by nicholasgriffintn** 2022-12-16 22:06 UTC
Labels: triage, feature-request
