### ISSUE TITLE
[Bug]: Version 8.1.5 of this library incompatible with @aws-sdk/client-sqs version 3.507.0

### ISSUE THREAD

**Issue by NihinFaj** [bbc/sqs-consumer#457] opened 2024-02-06 13:16 UTC
### Describe the bug

Version 8.1.5 of this library errors out when used with version 3.507.0 of @aws-sdk/client-sqs library.

 

### Your minimal, reproducible example

https://stackblitz.com/edit/sqs-consumer-starter-4nceen?file=index.js,package.json

### Steps to reproduce

1. Start new project
2. Install AWS SQS Client v3.507.0 
3. Install sqs-consumer v8.1.5
4. Try to initialise and consume messages from an SQS Queue

### Expected behavior

As a User
I expected to consume events from SQS using the sqs-consumer library

### How often does this bug happen?

None

### Screenshots or Videos

```
"err": {
        "type": "SQSError",
        "message": "SQS receive message failed: __importStar is not defined",
        "stack": "SQSError: SQS receive message failed: __importStar is not defined\n    at toSQSError (/service/dist/index.js:64873:24)\n    at Consumer2.receiveMessage (/service/dist/index.js:65143:41)",
        "name": "SQSError",
        "code": "ReferenceError",
        "time": "2024-02-05T14:24:27.109Z"
    }
```

### Platform

Node v18.17.1

### Package version

v8.1.5

### AWS SDK version

v3.507.0

**Comment by nicholasgriffintn** [comment] 2024-02-06 13:32
This is a major version change (AWS do it a little differently), we only support 3.4 onwards, we will look at the issues with 3.5, but for now, you should stick to 3.4 or above until a release for 3.5.

**Comment by nicholasgriffintn** [comment] 2024-02-06 18:32
On further investigation, I don't actually think this is the case, I've opened a draft PR here to run our tests, they're all passing including the E2E validation:

https://github.com/bbc/sqs-consumer/pull/458

Have you tested your code with an aws sdk version previous to 3.5? Your error references `__importStar` being undefined, to me, this looks like an internal component within your codebase.

I'd suggest checking through your codebase to be sure and downgrading your aws-sdk version if you haven't already.

Otherwise, if you are still getting issues, can you provide a full reproduction? If we can't reproduce it, we can't really do anything.

**Comment by thecodinglinguist** [comment] 2024-02-07 22:05
This has been an issue for us when using esbuild as of dynamic imports in >= 3.5. So this might not really related to sqs-consumer and instead be the project build tool.

**Comment by nicholasgriffintn** [comment] 2024-02-08 00:07
Yeah, possibly this: https://github.com/aws/aws-sdk-js-v3/issues/5750, which a patch was released for, closing s this doesn't appear to be an issue with the consumer but it is with aws sdk.

**Closed by nicholasgriffintn** 2024-02-08 00:07 UTC
Labels: bug, triage, needs reproduction
